Add logical NOT support
introproventures/graphql-jpa-query pull request #492
Opened 2024-07-17 14:28 UTC by MLSTRM

For #243 
Still testing this implementation some more on my own end within the projects I have just to confirm its doing exactly what I would expect, but the initial unit test results are promising.

2024-08-08 20:53 UTC, igdianov commented
@MLSTRM Thank you for opening a PR! Can you, please, run `mvn prettier:write` to format the code using prettier Java plugin to be able to run CI workflows?

2024-08-13 16:46 UTC, igdianov requested changes

2024-08-13 16:46 UTC, igdianov commented on schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/GraphQLJpaQueryFactory.java
> +                throw new RuntimeException("NOT expression cannot be applied to multiple predicates at once");
@MLSTRM It makes sense to apply `NOT: BoolExp` logical to single boolean expressions, i.e. `AND: [BoolExp]` / `OR: [BoolExp]`, but raising a runtime exception when `NOT` is a multi logical expression is not very kosher. It should be better to use GraphQl schema validation to fail fast if the request is not valid.

For example: 

```
AND: [BoolExp]
OR: [BoolExp]
EXISTS: [BoolExp]
NOT_EXISTS: [BoolExp]
NOT: BoolExp

```

2024-08-22 12:15 UTC, MLSTRM commented on schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/GraphQLJpaQueryFactory.java
> +                throw new RuntimeException("NOT expression cannot be applied to multiple predicates at once");
@igdianov I believe my changes in GraphQLJpaSchemaBuilder are doing this already, as everywhere the NOT field is being added it's using a singular GraphQLTypeReference rather than a List of such - the change here was more around logical completeness in case somehow you managed to find a way to sneak past it. The other possible way I was considering (but moved away from at least for my initial poc) was to have NOT be treated as a separate case and not use the existing getCompoundPredicate method at all which would remove the need for this branch, which I'm happy to look into if you'd prefer?

2024-08-27 04:28 UTC, igdianov commented on schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/GraphQLJpaQueryFactory.java
> +                throw new RuntimeException("NOT expression cannot be applied to multiple predicates at once");
Sorry, I overlooked the schema changes. It looks good and raising the runtime exception makes sense in case there something leaked through the cracks. :) 

I think it is better to add more test coverage for NOT: AND|OR|EXISTS use cases to be able to merge it. It will be easy to refactor the implementation later.

2024-08-28 16:15 UTC, igdianov approved these changes

2024-08-28 16:15 UTC, merged

2024-08-28 18:22 UTC, igdianov commented
LGTM. Thank you for the contribution! :)